### ISSUE TITLE
Does this tool support lif activation energy estimation? 

### ISSUE THREAD

**Issue by Michaeljurado24** [nengo/keras-spiking#19]
From what I can tell this tool only supports "relu". Is this accurate?

**Comment by drasmuss** [comment]
The energy estimates aren't specific to `relu`, but they also don't take into account different amounts of energy that might be used by different neuron types. We just assume a constant amount of energy per neural update, based on the published data. In the real world it is likely that something like LIF would require more energy than ReLU, since it's a more complicated calculation, but we don't know of any data that breaks that down in a more granular way.
